// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_oZ92572YoVRwb2g4G1TK4PyoMWQB1zY',
    appId: '1:169757099481:web:7a5b140fce1fc94019c5c8',
    messagingSenderId: '169757099481',
    projectId: 'com-example-phone-6a7e5',
    authDomain: 'com-example-phone-6a7e5.firebaseapp.com',
    storageBucket: 'com-example-phone-6a7e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvmWXtuR320xu97l2ZovlchAJnfOb1xU',
    appId: '1:169757099481:android:6e95785a642bfaf619c5c8',
    messagingSenderId: '169757099481',
    projectId: 'com-example-phone-6a7e5',
    storageBucket: 'com-example-phone-6a7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKcjJrm2d9My24KjyTca0pjtcAi-GgJM',
    appId: '1:169757099481:ios:56687d0b935bc4e519c5c8',
    messagingSenderId: '169757099481',
    projectId: 'com-example-phone-6a7e5',
    storageBucket: 'com-example-phone-6a7e5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKcjJrm2d9My24KjyTca0pjtcAi-GgJM',
    appId: '1:169757099481:ios:56687d0b935bc4e519c5c8',
    messagingSenderId: '169757099481',
    projectId: 'com-example-phone-6a7e5',
    storageBucket: 'com-example-phone-6a7e5.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_oZ92572YoVRwb2g4G1TK4PyoMWQB1zY',
    appId: '1:169757099481:web:fca4d047d068154319c5c8',
    messagingSenderId: '169757099481',
    projectId: 'com-example-phone-6a7e5',
    authDomain: 'com-example-phone-6a7e5.firebaseapp.com',
    storageBucket: 'com-example-phone-6a7e5.firebasestorage.app',
  );
}
